"""LTX-2.3 HQ pipeline — pure GPU architecture, no streaming.

Pre-fused checkpoint strategy:
- Stage 1: dev-fp8 checkpoint (29 GB), no LoRA → direct GPU load
- Stage 2: dev-fp8 + distilled LoRA pre-fused (29 GB) → direct GPU load
- Gemma: INT8 via bitsandbytes (13 GB) when available, else BF16 (25 GB)
- No CPU-to-GPU layer streaming
- No runtime LoRA fusion (baked into checkpoint)

GPU requirement: 32 GB (RTX 5090) — peak ~31 GB during transformer inference.
"""

import logging
import os
import tempfile
import time
import uuid

import torch

logger = logging.getLogger(__name__)

DEFAULT_NEGATIVE_PROMPT = (
    "worst quality, inconsistent motion, blurry, jittery, distorted, "
    "low resolution, watermark, text, oversaturated"
)

# Pre-fused checkpoint filename (generated by scripts/fuse_checkpoint.py)
FUSED_STAGE2_FILENAME = "ltx-2.3-22b-dev-lora08-fp8.safetensors"


def _round_to(value: int, divisor: int) -> int:
    return (value // divisor) * divisor


def _round_frames(n: int) -> int:
    return ((n - 1) // 8) * 8 + 1


class LTXVideoGenerator:
    """LTX-2.3 HQ video generator — pure GPU, no streaming.

    Uses TI2VidTwoStagesPipeline with:
    - Pre-fused FP8 checkpoints (no runtime LoRA fusion)
    - CFG guidance + negative prompts (full HQ quality)
    - No CPU-to-GPU layer streaming (direct GPU load)
    """

    def __init__(self, model_dir: str = "/models") -> None:
        # Stage 1: dev-fp8 checkpoint (no LoRA needed)
        stage1_path = os.path.join(model_dir, "ltx-2.3-22b-dev-fp8.safetensors")
        if not os.path.exists(stage1_path):
            # Fall back to BF16 dev checkpoint
            stage1_path = os.path.join(model_dir, "ltx-2.3-22b-dev.safetensors")
        if not os.path.exists(stage1_path):
            raise FileNotFoundError(
                f"No dev checkpoint found in {model_dir}. "
                "Run: python -m src.download_models"
            )

        # Stage 2: pre-fused checkpoint (LoRA baked in at strength=0.8)
        stage2_fused_path = os.path.join(model_dir, FUSED_STAGE2_FILENAME)
        has_fused = os.path.exists(stage2_fused_path)

        # LoRA for runtime fusion fallback (if pre-fused not available)
        distilled_lora_path = os.path.join(
            model_dir, "ltx-2.3-22b-distilled-lora-384.safetensors"
        )

        spatial_upsampler_path = os.path.join(
            model_dir, "ltx-2.3-spatial-upscaler-x2-1.1.safetensors"
        )
        gemma_root = os.path.join(model_dir, "gemma-3-12b-it-qat-q4_0-unquantized")

        logger.info("Initializing LTX-2.3 HQ pipeline (pure GPU) ...")
        if has_fused:
            logger.info("  Stage 1: %s", os.path.basename(stage1_path))
            logger.info("  Stage 2: %s (pre-fused, no runtime LoRA)", FUSED_STAGE2_FILENAME)
        else:
            logger.info("  Stage 1: %s", os.path.basename(stage1_path))
            logger.info("  Stage 2: runtime LoRA fusion (slower, needs more RAM)")
        self._log_vram("before pipeline init")

        from ltx_pipelines.ti2vid_two_stages import TI2VidTwoStagesPipeline
        from ltx_pipelines.utils.media_io import encode_video

        self._encode_video = encode_video

        # FP8 quantization policy — handles runtime FP8↔BF16 upcast in forward pass.
        # Still needed even with pre-quantized FP8 checkpoints for Fp8CastLinear wrappers.
        quantization = None
        try:
            from ltx_core.quantization import QuantizationPolicy
            quantization = QuantizationPolicy.fp8_cast()
            logger.info("  FP8 quantization policy enabled")
        except ImportError:
            logger.warning("  QuantizationPolicy not available")

        # CPU weight caching — reuse loaded weights across Stage 1 and Stage 2
        registry = None
        try:
            from ltx_core.loader import StateDictRegistry
            registry = StateDictRegistry()
            logger.info("  StateDictRegistry enabled (CPU weight caching)")
        except ImportError:
            pass

        # Enable torch.compile for faster transformer blocks
        use_compile = torch.cuda.is_available()

        # Build pipeline
        pipeline_kwargs = dict(
            checkpoint_path=stage1_path,
            spatial_upsampler_path=spatial_upsampler_path,
            gemma_root=gemma_root,
            loras=[],  # No base LoRAs
            torch_compile=use_compile,
        )
        if quantization is not None:
            pipeline_kwargs["quantization"] = quantization
        if registry is not None:
            pipeline_kwargs["registry"] = registry

        if has_fused:
            # Pre-fused: Stage 2 uses separate checkpoint, no LoRA fusion
            pipeline_kwargs["distilled_lora"] = []
            pipeline_kwargs["stage_2_checkpoint_path"] = stage2_fused_path
        else:
            # Fallback: runtime LoRA fusion (slower, needs streaming on <40 GB)
            from ltx_core.loader import (
                LTXV_LORA_COMFY_RENAMING_MAP,
                LoraPathStrengthAndSDOps,
            )
            pipeline_kwargs["distilled_lora"] = [
                LoraPathStrengthAndSDOps(
                    path=distilled_lora_path,
                    strength=0.8,
                    sd_ops=LTXV_LORA_COMFY_RENAMING_MAP,
                )
            ]

        self._pipeline = TI2VidTwoStagesPipeline(**pipeline_kwargs)
        self._has_fused = has_fused
        self._log_vram("after pipeline init")

        # Guider params
        self._MultiModalGuiderParams = None
        try:
            from ltx_core.components.guiders import MultiModalGuiderParams
            self._MultiModalGuiderParams = MultiModalGuiderParams
        except ImportError:
            pass

        # Tiling config
        self._TilingConfig = None
        self._get_video_chunks_number = None
        try:
            from ltx_core.model.video_vae import TilingConfig, get_video_chunks_number
            self._TilingConfig = TilingConfig
            self._get_video_chunks_number = get_video_chunks_number
        except ImportError:
            pass

        mode = "pre-fused GPU-only" if has_fused else "runtime LoRA (streaming fallback)"
        logger.info("Pipeline ready (%s).", mode)

    def _log_vram(self, label: str) -> None:
        if torch.cuda.is_available():
            alloc = torch.cuda.memory_allocated(0) / 1e9
            res = torch.cuda.memory_reserved(0) / 1e9
            logger.info("VRAM %s: %.2f GB allocated, %.2f GB reserved", label, alloc, res)

    @torch.inference_mode()
    def generate(
        self,
        prompt: str,
        negative_prompt: str = DEFAULT_NEGATIVE_PROMPT,
        width: int = 1024,
        height: int = 1536,
        num_frames: int = 121,
        num_inference_steps: int = 30,
        seed: int = 42,
        frame_rate: float = 24.0,
        cfg_scale: float = 3.0,
        stg_scale: float = 1.0,
        rescale_scale: float = 0.7,
    ) -> dict:
        """Run HQ inference and encode MP4."""
        width = _round_to(width, 64)
        height = _round_to(height, 64)
        num_frames = _round_frames(num_frames)
        job_id = uuid.uuid4().hex[:12]

        logger.info(
            "Job %s: prompt=%r, %dx%d, %d frames, %d steps, seed=%d",
            job_id, prompt[:80], width, height, num_frames, num_inference_steps, seed,
        )

        try:
            self._log_vram("before generation")
            start_time = time.time()

            # Guidance params — full HQ with CFG + STG
            video_guider_params = None
            audio_guider_params = None
            if self._MultiModalGuiderParams is not None:
                video_guider_params = self._MultiModalGuiderParams(
                    cfg_scale=cfg_scale, stg_scale=stg_scale,
                    rescale_scale=rescale_scale, modality_scale=3.0, stg_blocks=[28],
                )
                audio_guider_params = self._MultiModalGuiderParams(
                    cfg_scale=7.0, stg_scale=1.0, rescale_scale=0.7,
                    modality_scale=3.0, stg_blocks=[28],
                )

            # Tiling for large VAE decode
            tiling_config = None
            video_chunks_number = None
            if self._TilingConfig and self._get_video_chunks_number:
                tiling_config = self._TilingConfig.default()
                video_chunks_number = self._get_video_chunks_number(num_frames, tiling_config)

            # Streaming decision:
            # - Pre-fused: NO streaming (direct GPU load, no LoRA fusion)
            # - Runtime LoRA: streaming if <40 GB (LoRA fusion doubles memory)
            if self._has_fused:
                streaming = None
                max_batch = 1
                logger.info("Job %s: pure GPU mode (no streaming)", job_id)
            else:
                gpu_vram_gb = (
                    torch.cuda.get_device_properties(0).total_memory / 1e9
                    if torch.cuda.is_available() else 0
                )
                streaming = 2 if gpu_vram_gb < 40 else None
                max_batch = 4 if streaming else 1
                if streaming:
                    logger.info(
                        "Job %s: streaming fallback (GPU %.0f GB, no pre-fused checkpoint)",
                        job_id, gpu_vram_gb,
                    )

            call_kwargs = dict(
                prompt=prompt, negative_prompt=negative_prompt, seed=seed,
                height=height, width=width, num_frames=num_frames,
                frame_rate=frame_rate, num_inference_steps=num_inference_steps,
                images=[],
                streaming_prefetch_count=streaming,
                max_batch_size=max_batch,
            )
            if video_guider_params is not None:
                call_kwargs["video_guider_params"] = video_guider_params
            if audio_guider_params is not None:
                call_kwargs["audio_guider_params"] = audio_guider_params
            if tiling_config is not None:
                call_kwargs["tiling_config"] = tiling_config

            result = self._pipeline(**call_kwargs)
            video, audio = result if isinstance(result, tuple) else (result, None)
            generation_time = time.time() - start_time
            logger.info("Job %s: generation took %.1fs", job_id, generation_time)
            self._log_vram("after generation")

            # Encode video
            output_filename = f"ltx_{job_id}.mp4"
            output_path = os.path.join(tempfile.gettempdir(), output_filename)
            encode_kwargs = dict(video=video, fps=int(frame_rate), output_path=output_path)
            if audio is not None:
                encode_kwargs["audio"] = audio
            if video_chunks_number is not None:
                encode_kwargs["video_chunks_number"] = video_chunks_number
            self._encode_video(**encode_kwargs)

            return {
                "output_path": output_path,
                "output_filename": output_filename,
                "generation_time_seconds": round(generation_time, 2),
                "parameters": {
                    "width": width, "height": height, "num_frames": num_frames,
                    "num_inference_steps": num_inference_steps, "seed": seed,
                    "frame_rate": frame_rate, "cfg_scale": cfg_scale,
                    "stg_scale": stg_scale, "rescale_scale": rescale_scale,
                },
            }

        except Exception:
            logger.exception("Job %s failed", job_id)
            torch.cuda.empty_cache()
            raise
